// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Shopping_System.Data;

#nullable disable

namespace Online_Shopping_System.Migrations
{
    [DbContext(typeof(OnlineShoppingContext))]
    partial class OnlineShoppingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Online_Shopping_System.Models.Carts.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<string>("CartStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Carts.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Orders.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Payment.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Products.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Shipping.ShippingRecords", b =>
                {
                    b.Property<int>("ShippingRecordsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingRecordsId"));

                    b.Property<DateTimeOffset>("DeleveredTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShippingTypeId")
                        .HasColumnType("int");

                    b.HasKey("ShippingRecordsId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ShippingTypeId")
                        .IsUnique();

                    b.ToTable("ShippingRecords", (string)null);
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Shipping.ShippingType", b =>
                {
                    b.Property<int>("ShippingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingTypeId"));

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShippingDuration")
                        .HasColumnType("int");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShippingTypeId");

                    b.ToTable("ShippingTypes", (string)null);
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Users.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeId"));

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserTypes", (string)null);
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Payment.CashPayment", b =>
                {
                    b.HasBaseType("Online_Shopping_System.Models.Payment.Payment");

                    b.ToTable("CashPayments", (string)null);
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Payment.CreditCardPayment", b =>
                {
                    b.HasBaseType("Online_Shopping_System.Models.Payment.Payment");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CreditCardPayments", (string)null);
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Payment.WalletPayment", b =>
                {
                    b.HasBaseType("Online_Shopping_System.Models.Payment.Payment");

                    b.Property<string>("WalletNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WalletProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("WalletPayments", (string)null);
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Products.Books", b =>
                {
                    b.HasBaseType("Online_Shopping_System.Models.Products.Product");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Products.Clothes", b =>
                {
                    b.HasBaseType("Online_Shopping_System.Models.Products.Product");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.ToTable("Clothes", (string)null);
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Products.Electronics", b =>
                {
                    b.HasBaseType("Online_Shopping_System.Models.Products.Product");

                    b.Property<double>("Warranty")
                        .HasColumnType("float");

                    b.ToTable("Electronics", (string)null);
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Carts.Cart", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Users.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Online_Shopping_System.Models.Carts.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Carts.CartItem", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Carts.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Shopping_System.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Orders.Order", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Carts.Cart", "Cart")
                        .WithOne("Order")
                        .HasForeignKey("Online_Shopping_System.Models.Orders.Order", "CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Online_Shopping_System.Models.Users.User", "User")
                        .WithMany("Order")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Payment.Payment", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Shipping.ShippingRecords", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Orders.Order", "Order")
                        .WithOne("ShippingRecords")
                        .HasForeignKey("Online_Shopping_System.Models.Shipping.ShippingRecords", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Shopping_System.Models.Shipping.ShippingType", "ShippingType")
                        .WithOne("ShippingRecords")
                        .HasForeignKey("Online_Shopping_System.Models.Shipping.ShippingRecords", "ShippingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ShippingType");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Users.User", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Users.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Payment.CashPayment", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Payment.Payment", null)
                        .WithOne()
                        .HasForeignKey("Online_Shopping_System.Models.Payment.CashPayment", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Payment.CreditCardPayment", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Payment.Payment", null)
                        .WithOne()
                        .HasForeignKey("Online_Shopping_System.Models.Payment.CreditCardPayment", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Payment.WalletPayment", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Payment.Payment", null)
                        .WithOne()
                        .HasForeignKey("Online_Shopping_System.Models.Payment.WalletPayment", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Products.Books", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Products.Product", null)
                        .WithOne()
                        .HasForeignKey("Online_Shopping_System.Models.Products.Books", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Products.Clothes", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Products.Product", null)
                        .WithOne()
                        .HasForeignKey("Online_Shopping_System.Models.Products.Clothes", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Products.Electronics", b =>
                {
                    b.HasOne("Online_Shopping_System.Models.Products.Product", null)
                        .WithOne()
                        .HasForeignKey("Online_Shopping_System.Models.Products.Electronics", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Carts.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Order")
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Orders.Order", b =>
                {
                    b.Navigation("ShippingRecords")
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Shipping.ShippingType", b =>
                {
                    b.Navigation("ShippingRecords")
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Users.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Online_Shopping_System.Models.Users.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
